volumes:
  db_volume:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always

  line-provider:
    build: ./line-provider
    env_file: .env
    restart: always

  bet-maker:
    build: ./bet-maker
    env_file: .env
    depends_on:
      - db
      - line-provider
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - ${NGINX_HOST_PORT}:80
    depends_on:
      - bet-maker
      - line-provider
    restart: always